# Serveur FTP accessible via le port 2121.
# Seul le mode passif est supporté (limite de basic-ftp, pas de mode actif).

services:
  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: ftp
    volumes:
      # Répertoire racine de l'utilisateur test3
      - ./data-test:/home/test3/landing-zone
    ports:
      - "2121:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: test3
      FTP_USER_PASS: 12345
      FTP_USER_HOME: /home/test3
